require("stbaunchained.remap")
require("stbaunchained.packer")
require("stbaunchained.set")
-- vim.wo.number = true
require("ibl").setup()
require('Comment').setup()
require("stbaunchained.lsp")
require("stbaunchained.harpoon")
require("stbaunchained.undotree")
require("stbaunchained.fugitive")
